# Generated by Django 3.2.12 on 2022-04-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='totalrating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='book_new',
            name='totalrating',
            field=models.FloatField(default=5),
        ),
    ]
